apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferretdb-chart.fullname" . }}-ferretdb
  labels:
    app: {{ include "ferretdb-chart.name" . }}
spec:
  type: {{ .Values.ferretdb.service.type }}
  selector:
    app: {{ include "ferretdb-chart.name" . }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.ferretdb.service.port }}
      targetPort: {{ .Values.ferretdb.service.port }}

